#!/usr/bin/env Rscript

#### ENV SET-UP AND ARGUMENTS ####
##### Loading packages silently #####
# Check if one of .libPaths() is writable for the user, and if not, create a writable package library in $HOME (~)
source("~/Rfunctions/check_libPaths.R")
writable_path <- check_libPaths(verbose = FALSE)
# Install/load pacman.
suppressPackageStartupMessages(if (!require(pacman)) {
    install.packages("pacman", lib = writable_path)
})
needed_packs <- c(  "tidyverse", "plyr", "ggplot2", "vegan", "gridExtra", "ggplotify", "ggpubr", "ggtext", "ggforce", "multcompView",
                    "cli", "argparser", "spaa", "apeglm", "this.path", "patchwork", "rio", "abdiv", "picante", "tidytree") 
to_install <- needed_packs[!needed_packs %in% pacman::p_library()]
message("Installing and/or loading required packages...")
if (length(to_install) != 0) {
    pacman::p_install(to_install, character.only = TRUE, try.bioconductor = TRUE, path = writable_path)
}
pacman::p_load(needed_packs, character.only = TRUE)
#github_packs <- c("benjjneb/dada2")
#pacman::p_load_gh(github_packs)

##### Set WD, source functions and variables #####
script_dir <- this.dir() # gets dir where the script is stored
function_dir <- paste0(script_dir, "/functions/")
working_dir <- getinitwd() # gets dir from where the script is launched
source(paste0(function_dir, "/alpha_diversity.R"))

##### Parse arguments with arg_parser #####
cli_h1("Parsing input")
parser <- arg_parser("Check the compatibility of the data (count table, metadata, taxonomy file).")
parser <- add_argument(parser, "counttable", help = "Count table with absolute abundances for each taxon (5_taxonomy.R output)")
parser <- add_argument(parser, "taxonomy", help = "Taxonomy table outputted by 5_taxonomy.R")
parser <- add_argument(parser, "metadata", help = "Metadata file, where Sample_Name column contains sample names exactly as colnames in counttable")
parser <- add_argument(parser, "filtered", help = "Path to filtered_list.RData file, generated by 6.2_filter_transform.R")
parser <- add_argument(parser, "--tree", help = "Path to tree file (nwk) of the ASV sequences. If none supplied, no phylogenetic alpha-diversity will be computed.", default = "None")
parser <- add_argument(parser, "--outdir", help = "Output directory for all the following steps.")
argv <- parse_args(parser)

##### Communicate arguments #####
cli_alert_success("Parsed arguments successfully: ")
cli_li("count table -> {argv$counttable}")
cli_li("filtered_list -> {argv$filtered}")
cli_li("taxonomy -> {argv$taxonomy}")
cli_li("metadata -> {argv$metadata}")
cli_li("tree -> {argv$tree}")

##### Create output directory if necessary #####
outdir <- file.path(argv$outdir)
if (!dir.exists(outdir)) {
    dir.create(outdir, recursive = TRUE)
    cli_alert_info("Output directory {outdir} doesn't exist, creating it.")
} else {
    cli_alert_info("Output directory {outdir} already exists.")
}
##### Load data #####
count_table <- rio::import(argv$counttable) %>% column_to_rownames("V1")
taxonomy <- rio::import(argv$taxonomy) %>% column_to_rownames("V1")
metadata <- rio::import(argv$metadata) %>% column_to_rownames("V1")
tree <- tidytree::read.tree(argv$tree)

##### Set which taxons #####
taxons <- c("phylum", "class", "order", "family", "genus", "species")